"""Initial migration

Revision ID: f106c2b1c3bc
Revises: 
Create Date: 2024-12-30 19:10:10.486587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f106c2b1c3bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simpul',
    sa.Column('id_simpul', sa.Integer(), nullable=False),
    sa.Column('nama_simpul', sa.String(length=100), nullable=True),
    sa.Column('jenis_simpul', sa.Enum('TPS', 'TPA', 'JALAN'), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('id_simpul')
    )
    op.create_table('armada',
    sa.Column('id_armada', sa.Integer(), nullable=False),
    sa.Column('plat_nomor', sa.String(length=20), nullable=True),
    sa.Column('alamat_armada', sa.String(length=255), nullable=True),
    sa.Column('kapasitas', sa.Integer(), nullable=True),
    sa.Column('id_simpul', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_simpul'], ['simpul.id_simpul'], ),
    sa.PrimaryKeyConstraint('id_armada')
    )
    op.create_table('graf',
    sa.Column('id_graf', sa.Integer(), nullable=False),
    sa.Column('id_simpul_mulai', sa.Integer(), nullable=True),
    sa.Column('id_simpul_tujuan', sa.Integer(), nullable=True),
    sa.Column('jarak', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_simpul_mulai'], ['simpul.id_simpul'], ),
    sa.ForeignKeyConstraint(['id_simpul_tujuan'], ['simpul.id_simpul'], ),
    sa.PrimaryKeyConstraint('id_graf')
    )
    op.create_table('tpa',
    sa.Column('id_tpa', sa.Integer(), nullable=False),
    sa.Column('nama_tpa', sa.String(length=100), nullable=True),
    sa.Column('alamat_tpa', sa.String(length=255), nullable=True),
    sa.Column('id_simpul', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_simpul'], ['simpul.id_simpul'], ),
    sa.PrimaryKeyConstraint('id_tpa')
    )
    op.create_table('tps',
    sa.Column('id_tps', sa.Integer(), nullable=False),
    sa.Column('nama_tps', sa.String(length=100), nullable=True),
    sa.Column('alamat_tps', sa.String(length=255), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('id_simpul', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_simpul'], ['simpul.id_simpul'], ),
    sa.PrimaryKeyConstraint('id_tps')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tps')
    op.drop_table('tpa')
    op.drop_table('graf')
    op.drop_table('armada')
    op.drop_table('simpul')
    # ### end Alembic commands ###
